include: package:very_good_analysis/analysis_options.yaml

# analyzer:
#   exclude:
#     - lib/src/generated/**
#     - test/integration/test_tools/serverpod_test_tools.dart
#     - lib/src/models/sample-data/**

linter:
  rules:
    lines_longer_than_80_chars: false
