name: flutter_vscode
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^10.0.1
  build: ^4.0.3
  flutter:
    sdk: flutter
  meta: ^1.9.1
  path: ^1.8.3
  source_gen: ^4.1.1
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.10.4
  build_test: ^3.5.4
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  very_good_analysis: ^10.0.0

executables:
  generate_vscode_extension: generate_vscode_extension
