name: treemap_panel
publish_to: none

environment:
  sdk: ^3.12.0

dependencies:
  coverage_treemap_shared:
    path: ../../shared
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_vscode:
    path: ../../../..
  flutter_web_plugins:
    sdk: flutter
