name: pubspec_lens_host
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  flutter_vscode:
    path: ../../../packages/flutter_vscode
  pubspec_lens_shared:
    path: ../shared

dev_dependencies:
  very_good_analysis: ^10.0.0
